use sha2::{Sha256, Digest};
use serde::Deserialize;
use std::collections::HashMap;
use std::io::Write;

#[derive(Deserialize)]
struct VaultEntry {
    #[allow(dead_code)]
    id: String,
    #[allow(dead_code)]
    title: String,
    #[allow(dead_code)]
    category: String,
    #[allow(dead_code)]
    placeholders: Vec<String>,
    prompt: String,
}

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=prompts/core_vault.toml");

    // --- Prompt Vault Hash Generation ---
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let hashes_path = std::path::Path::new(&out_dir).join("prompt_hashes.rs");
    let mut hashes_file = std::fs::File::create(&hashes_path).unwrap();

    let toml_path = std::path::Path::new("prompts/core_vault.toml");
    if toml_path.exists() {
        let content = std::fs::read_to_string(toml_path).unwrap();
        let parsed: HashMap<String, VaultEntry> = toml::from_str(&content).unwrap_or_default();

        let mut entries = Vec::new();
        for (slug, entry) in &parsed {
            let mut hasher = Sha256::new();
            hasher.update(entry.prompt.as_bytes());
            let hash = format!("{:x}", hasher.finalize());
            entries.push(format!("    (\"{}\", \"{}\")", slug, hash));
        }

        writeln!(hashes_file, "/// SHA-256 hashes of core prompts, computed at build time from core_vault.toml").unwrap();
        writeln!(hashes_file, "/// DO NOT EDIT — this file is auto-generated by build.rs").unwrap();
        writeln!(hashes_file, "pub const CORE_PROMPT_HASHES: &[(&str, &str)] = &[").unwrap();
        writeln!(hashes_file, "{}", entries.join(",\n")).unwrap();
        writeln!(hashes_file, "];").unwrap();

        println!("cargo:warning=Prompt Vault: {} hashes SHA-256 compilados.", parsed.len());
    } else {
        // Fallback: array vazio (DB mantém prompts do último seed)
        writeln!(hashes_file, "pub const CORE_PROMPT_HASHES: &[(&str, &str)] = &[];").unwrap();
        println!("cargo:warning=Prompt Vault: core_vault.toml não encontrado. Hashes vazios.");
    }
}
