name: Auto Release Notes

on:
  push:
    tags:
      - 'v*' # Aciona o workflow apenas quando criar tags como v1.0.0

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necessario para criar releases
    steps:
      - name: Checkout Code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          fetch-depth: 0 # Busca todo o historico para os changelogs

      - name: Generate Changelog and Create Release
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2.6.1
        with:
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
